name: CD - Entrega do Sistema

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Enviar sistema como Artifact
        uses: actions/upload-artifact@v7
        with:
          name: chamados-ti
          path: chamados-ti/